version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn hw13_fastapi_app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
